### Site metadata ###

title: Juniper Networks Automation

repository: bgriffin-/bgriffin-.github.io
author: Ben Griffin
twitter_handle: #some_twitter_handle

### Build settings ###

url: https://bgriffin-.netlify.app
baseurl: ""

theme: jekyll-bulma

permalink: pretty

header_pages:
  - repos.md
  - topics.md
  - datacenter.md
  - security.md
  - wan.md
  - about.md

collections:
  topics:
    output: true

liquid:
  strict_filters: true

exclude:
  - docs/
  - LICENSE
  - README.md
  - Makefile
  - netlify.toml
  - package.json
  - package-lock.json