name: Github Pages Deploy

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache to Shorten Build Time
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Set-up jekyll
        uses: helaili/jekyll-action@2.0.5
        with:
          # token: ${{secrets.GITHUB_TOKEN}}
          target_branch: 'gh-pages'
      # - run: npm install
      # - run: npm run build
      # - run: npm test
      # - name: Deploy
      #   uses: crazy-max/ghaction-github-pages@v1
      #   with:
      #     target_branch: gh-pages
      #     build_dir: build
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


          